name = "RxGP"
uuid = "8e06354a-9460-4f50-98fd-90b481720b65"
authors = ["HoangMHNguyen <m.h.n.hoang@tue.nl> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
